name: Building(CMake)

on:
  push:
    branches: [ master ]
    paths-ignore:
    #   - 'README.md'
      - 'README_zh.md'
      - 'LICENSE'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'README_zh.md'
      - 'LICENSE'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  linux-build:
    name: ${{ matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - name: Checkout Source code
        if: github.event_name == 'push'
        uses: actions/checkout@v4
        with:
            submodules: true

      - name: Checkout Source code
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: true

      - name: Install Dependencies
        run: |
          sudo apt-get -y -qq update
          sudo apt-get -y --no-install-recommends install \
            cmake \
            extra-cmake-modules \
            build-essential \
            qtbase5-dev \
            qttools5-dev-tools \
            qttools5-dev \
            libqt5dbus5 \
            libqt5network5 \
            libqt5core5a \
            libqt5widgets5 \
            libqt5gui5 \
            libqt5svg5-dev

      - name: Configure CMake
        shell: bash
        run: cmake -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        # working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Test
        # working-directory: ${{runner.workspace}}/build
        shell: bash
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C $BUILD_TYPE

  windows-build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows 2019 MSVC",
            artifact: "Windows-MSVC.tar.xz",
            os: windows-2019,
            cc: "cl", cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }

    steps:
      - uses: actions/checkout@v4
        with:
            submodules: true

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v3
        with:
          path: ./build/Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.2
          target:  desktop
          dir: '${{ github.workspace }}/build/'

      - name: Configure CMake
        working-directory: build
        shell: powershell
        run: |
          cmake -DCMAKE_BUILD_TYPE=$env:BUILD_TYPE ../

      - name: Build
        working-directory: build
        shell: powershell
        run: |
          cmake --build . --config $env:BUILD_TYPE