name: linux-package

on:
  push:
    tags:
      - 'v*'

jobs:
  platform-build:
    # Because linuxdeployqt only supports ubuntu 22.04, not support higher version like 24.04
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    env:
      QT_VERSION: 6.8.0
      BUILD_TYPE: Release

    steps:
      - name: Checkout Source code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          cache: true
          cache-key-prefix: 'Qt'

      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}          

      - name: Install AppImage dependencies (Linux)
        # Ubuntu (>= 24.04) is libfuse2t64, otherwise is libfuse2
        run: |
          UBUNTU_VER=$(lsb_release -rs)   # 24.04 / 22.04 / 20.04
          echo "Ubuntu $UBUNTU_VER detected"

          case "$UBUNTU_VER" in
            24.04)
              sudo apt-get install -y libfuse2t64
              ;;
            22.04)
              sudo apt-get install -y libfuse2
              ;;
            *)
              echo "Untested Ubuntu version: $UBUNTU_VER"
              ;;
          esac
          
      - name: Run Packaging Script (Linux)
        run: |
          python3 scripts/build_linux_package.py --output-dir ${{ github.workspace }}/build/src --app-name QClipboard --format appimage
          
      # # For CD test  
      # - name: Upload Linux AppImage as Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: QClipboard-Linux-AppImage
      #     path: ${{ github.workspace }}/build/src/QClipboard*.AppImage
      #     retention-days: 7
          
      - name: Create Release and Upload Artifacts
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.workspace }}/build/src/QClipboard*.AppImage
          draft: false
          prerelease: false
          generate_release_notes: true